spring:
  thymeleaf:
    cache: true
    prefix: classpath:/views/
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/reuse?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: reuse
    password: 2zsNZsAN5RCMFxFz
#    开启post
  mvc:
    hiddenmethod:
      filter:
        enabled: true